backend:
  name: github
  repo: nellydundy/mi-vida-mi-ritmo
  branch: main
  auth_type: pkce
  base_url: https://auth.decapcms.org
  site_url: https://mi-vida-mi-ritmo.netlify.app

media_folder: "static/img"             # carpeta local para imágenes
public_folder: "/img"                  # ruta pública de imágenes en la web

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"            # carpeta donde se guardan los archivos Markdown
    create: true                        # permite crear nuevos posts desde el CMS
    slug: "{{slug}}"                    # nombre automático del archivo basado en el título
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
